<?php
/**
 * Created by PhpStorm.
 * User: Wang Zhijie
 * Date: 2019/3/2
 * Time: 17:22
 */

namespace frontend\controllers;

use common\models\Article;
use common\models\CatModel;
use common\models\PostModel;
use frontend\controllers\base\BaseController;
use frontend\models\PostForm;
use Yii;
use yii\data\Pagination;

class PostController extends BaseController
{

    //文章列表
    public function actionIndex()
    {
//        return $this->render('index'); // TODO: Change the autogenerated stub

        return $this->render('index');
    }

    public function actionView($id)
    {

        $post = PostModel::find()->where('id=:id',[":id"=>$id])->one();
        return $this->render('view',["post"=>$post]);

    }


    /**
     * @return string 创建文章
     */
    public function actionCreate()
    {
        $model = new PostForm();
        //获取所有分类
        $cat = CatModel::getAllCats();
        return $this->render('create', ['model' => $model, 'cat' => $cat]
        );
    }

    public function actionCategory($cat_id)
    {
        $post = PostModel::find()->where('cat_id=:cat_id',[":cat_id"=>$cat_id])->all();
        return $this->render('category',['post'=>$post]);

    }
}