<?php
/**
 * Created by PhpStorm.
 * User: Wang Zhijie
 * Date: 2019/3/2
 * Time: 17:22
 */

namespace frontend\controllers;

use common\models\Article;
use common\models\Category;
use common\models\CatModel;
use common\models\Comment;
use common\models\PostModel;
use common\models\User;
use frontend\controllers\base\BaseController;

use frontend\models\CommentForm;
use frontend\models\PostForm;
use Yii;
use yii\data\Pagination;
use yii\db\Exception;

class PostController extends BaseController
{

    //文章列表
    public function actionIndex()
    {
//        return $this->render('index'); // TODO: Change the autogenerated stub
        return $this->render('index');
    }

    public function actionView($id)
    {

        $post = PostModel::find()->where('id=:id',[":id"=>$id])->one();
        $user = Yii::$app->getUser();

        $comments = Comment::find()->where('post_id=:id',[":id"=>$id])->all();
        $user_info = User::find()->all();
        $user_array = array();
        $cat = Category::find()->where('id=:id',[':id'=>$post->cat_id])->one();
        foreach ($user_info as $item)
        {
            $user_array[$item->id] = $item->username;
        }
        $commentForm = new CommentForm();

        if($commentForm->load(Yii::$app->request->post()) && $commentForm->validate())
        {

            try {
                Yii::$app->db->createCommand()->insert('comment', [
                    'post_id' => $id,
                    'user_id'=> $user->id,
                    'comment' => $commentForm->comment,
                ])->execute();
                $comments = Comment::find()->where('post_id=:id',[":id"=>$id])->all();
            } catch (Exception $e) {
            }
            return $this->render('view',[
                "post"=>$post ,
                'comments'=>$comments,
                'user'=>$user ,
                'commentForm'=>$commentForm,
                "user_array"=>$user_array,
                "cat"=>$cat
            ]);

        }
        return $this->render('view',[
            "post"=>$post ,
            'comments'=>$comments,
            'user'=>$user ,
            'commentForm'=>$commentForm,
            "user_array"=>$user_array,
            'cat'=>$cat
            ]);

    }


    /**
     * @return string 创建文章
     */
    public function actionCreate()
    {
        $model = new PostForm();
        //获取所有分类
        $cat = CatModel::getAllCats();
        return $this->render('create', ['model' => $model, 'cat' => $cat]
        );
    }

    public function actionCategory($cat_id)
    {
        $post = PostModel::find()->where('cat_id=:cat_id',[":cat_id"=>$cat_id])->all();
        $cat = Category::find()->where('id=:cat_id',[":cat_id"=>$cat_id])->one();
        return $this->render('category',[
            'post'=>$post,
            'cat'=>$cat
        ]);

    }


}