<?php
/**
 * Created by PhpStorm.
 * User: Wang Zhijie
 * Date: 2019/3/2
 * Time: 20:36
 */

namespace frontend\models;

use common\models\PostModel;
use yii\base\Model;

/**
 * 文章表单模型
 */

class PostForm extends Model
{
    public $id;
    public $title;
    public $content;
    public $label_img;
    public $cat_id;
    public $tags;
    public $_lastError = "";

    public function rules()
    {
        return [
            [['id','title','content','cat_id'],'required'],
            [['id','cat_id'],'integer'],
            ['title','string','min'=>4,'max'=>50],

        ]; // TODO: Change the autogenerated stub

    }


/*    public function rules(){
        return [
            [['id','title','content','cat_id'],'required'],
            [['id','cat_id'],'integer'],
            ['title','string','min'=>4,'max'=>50]
        ];
    }*/


    public function attributeLabels()
    {
        return [
            'id'=>'编码',
            'title'=>'标题',
            'content'=>'内容',
            'label_img'=>'缩略图',
            'tags'=>'标签',
            'cat_id'=>'分类号'
        ]; // TODO: Change the autogenerated stub
    }

    public static function getList($cond,$curPage = 1,$pageSize = 5,$orderBy = ['id'=>SORT_DESC])
    {
        $model = new PostModel();
        $select = ['id','title','summary','label_imag','cat_id','user_id','user_name','is_valid','created_at','updated_at'];
        $query = $model->find()
            ->select($select)
            ->where($cond)
            ->orderBy($orderBy);

        $res = $model->getPages($query,$curPage,$pageSize);

        $res['data'] = self::_formatList($res['data']);

        return $res;

    }

    public static function _formatList($data)
    {
        foreach ($data as &$list)
        {
            $list['tags'] = [];
            if(isset($list['relate']) && !empty($list['relate']))
            {
                foreach ($list['relate'] as $lt)
                {
                    $list['tags'][] = $lt['tag']['tag_name'];
                }
            }

            unset($list['relate']);
        }
        return $data;
    }
}